apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: awx-postgres-restore
  namespace: postgres-awx
  annotations:
    argocd.argoproj.io/sync-wave: "2"  # Install after secrets
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16.2

  storage:
    storageClass: local-path
    size: 5Gi

  walStorage:
    storageClass: local-path
    size: 5Gi

  # Bootstrap via recovery from an existing cluster’s backup
  bootstrap:
    recovery:
      source: awx-postgres       # Must match the externalClusters[].name
      # Uncomment for PITR:
      # recoveryTarget:
      #   targetTime: "2025-10-08T15:00:00Z"

  # External cluster definition – points to backup storage (MinIO/S3)
  externalClusters:
    - name: awx-postgres
      barmanObjectStore:
        destinationPath: s3://postgres-backup/awx-backups/    # match original
        endpointURL: http://192.168.65.8:9000                # replace with MinIO/S3 endpoint
        s3Credentials:
          accessKeyId:
            name: backup-credentials
            key: ACCESS_KEY_ID
          secretAccessKey:
            name: backup-credentials
            key: ACCESS_SECRET_KEY
        wal:
          compression: gzip
          maxParallel: 2


  monitoring:
    enablePodMonitor: true

  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "2"
