apiVersion: v1
kind: Secret
metadata:
  name: awx-postgres-credentials
  namespace: postgres-awx
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: kubernetes.io/basic-auth
stringData:
  username: awx
  password: "awx"
---
apiVersion: v1
kind: Secret
metadata:
  name: backup-credentials
  namespace: postgres-awx
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  ACCESS_KEY_ID: "minioadmin"
  ACCESS_SECRET_KEY: "minioadmin"
