apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
  - namespace.yaml
  - install.yaml

patches:
  - path: patches/argocd-server-patch.yaml
    target:
      kind: Service
      name: argocd-server
      labelSelector: app.kubernetes.io/component=server
